substitutions:
  _NEXT_PUBLIC_API_BASE_URL: "https://default.example.com"  # dummy

steps:
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "NEXT_PUBLIC_API_BASE_URL=$_NEXT_PUBLIC_API_BASE_URL" > .env.production
        npm install
        npm run build

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-fe", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-fe"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "fe",
        "--image",
        "gcr.io/$PROJECT_ID/tcc-fe",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars=NEXT_PUBLIC_API_BASE_URL=$_NEXT_PUBLIC_API_BASE_URL"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
